## Table_1
CREATE OR REPLACE TABLE TABLE_1 (ID VARCHAR2(10));

INSERT INTO TABLE_1 (ID) VALUES ('1'), ('1'), ('1'),('2'),('3'),('3'),(NULL),('A');

SELECT * FROM TABLE_1;

## Table_2
CREATE OR REPLACE TABLE TABLE_2 (ID VARCHAR2(10));

INSERT INTO TABLE_2 (ID) VALUES ('1'), ('1'), ('2'),('2'),('4'),('A'),(NULL),(NULL);

SELECT * FROM TABLE_2;

--INNER JOIN

SELECT T1.ID, 
       T2.ID
FROM TABLE_1 AS T1

INNER JOIN TABLE_2 AS T2
ON T1.ID = T2.ID;

-- LEFT JOIN

SELECT T1.ID, 
       T2.ID
FROM TABLE_1 AS T1

LEFT JOIN TABLE_2 AS T2
ON T1.ID = T2.ID;

--RIGHT JOIN


SELECT T1.ID, 
       T2.ID
FROM TABLE_1 AS T1

RIGHT JOIN TABLE_2 AS T2
ON T1.ID = T2.ID;

--FULL JOIN


SELECT T1.ID, 
       T2.ID
FROM TABLE_1 AS T1

FULL JOIN TABLE_2 AS T2
ON T1.ID = T2.ID;

--CROSS JOIN


SELECT T1.ID, 
       T2.ID
FROM TABLE_1 AS T1

CROSS JOIN TABLE_2 AS T2;
